package org.acme.model;

import jakarta.validation.constraints.*;
import jakarta.validation.Valid;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Gets or Sets ErrorCode
 */
public enum ErrorCode {
  
  UNKNOWN_TECHNICAL_EXCEPTION("UNKNOWN_TECHNICAL_EXCEPTION"),
  
  AUTHENTICATION_FAILED("AUTHENTICATION_FAILED"),
  
  UNAUTHORIZED("UNAUTHORIZED"),
  
  SESSION_EXPIRED("SESSION_EXPIRED"),
  
  BUSINESS_RELATION_OFFER_SEND_MAIL_EXCEPTION("BUSINESS_RELATION_OFFER_SEND_MAIL_EXCEPTION"),
  
  COLLI_WARN_QUOTA_SEND_MAIL_EXCEPTION("COLLI_WARN_QUOTA_SEND_MAIL_EXCEPTION"),
  
  NUMBER_RANGE_WARNING_QUOTA_SEND_MAIL_EXCEPTION("NUMBER_RANGE_WARNING_QUOTA_SEND_MAIL_EXCEPTION"),
  
  SEND_PASSWORD_RESET_MAIL_EXCEPTION("SEND_PASSWORD_RESET_MAIL_EXCEPTION"),
  
  SEND_FEATURE_ACTIVATION_MAIL_EXCEPTION("SEND_FEATURE_ACTIVATION_MAIL_EXCEPTION"),
  
  DOMAIN_OBJECT_NOT_FOUND("DOMAIN_OBJECT_NOT_FOUND"),
  
  CONSTRAINT_VIOLATION("CONSTRAINT_VIOLATION"),
  
  CONCURRENT_ACCESS("CONCURRENT_ACCESS"),
  
  ILLEGAL_PATCH_OPERATION("ILLEGAL_PATCH_OPERATION"),
  
  ILLEGAL_ACCESS("ILLEGAL_ACCESS"),
  
  INCONSISTENT_DATA("INCONSISTENT_DATA"),
  
  MANDATORY_PARAMETER_NOT_SET("MANDATORY_PARAMETER_NOT_SET"),
  
  DOMAIN_OBJECT_CONFLICT("DOMAIN_OBJECT_CONFLICT"),
  
  WRONG_ORDER_STATE("WRONG_ORDER_STATE"),
  
  WRONG_LOADINGLIST_STATE("WRONG_LOADINGLIST_STATE"),
  
  WRONG_LOADINGLIST_DATE("WRONG_LOADINGLIST_DATE"),
  
  WRONG_LOADINGLIST_EDI_STATE("WRONG_LOADINGLIST_EDI_STATE"),
  
  LOADINGLIST_NOT_FOUND_BY_ID("LOADINGLIST_NOT_FOUND_BY_ID"),
  
  PROCUREMENTORDER_NOT_FOUND_BY_ID("PROCUREMENTORDER_NOT_FOUND_BY_ID"),
  
  WRONG_PROCUREMENTORDER_EDI_STATE("WRONG_PROCUREMENTORDER_EDI_STATE"),
  
  CANNOT_REOPEN_ORDER_ON_LOADING_LIST("CANNOT_REOPEN_ORDER_ON_LOADING_LIST"),
  
  CANNOT_CREATE_EMPTY_LOADING_LIST("CANNOT_CREATE_EMPTY_LOADING_LIST"),
  
  CANNOT_CREATE_LOADING_LIST_DATE_IN_PAST("CANNOT_CREATE_LOADING_LIST_DATE_IN_PAST"),
  
  CANNOT_CREATE_LOADING_LIST_WITHOUT_LOADING_PLACE("CANNOT_CREATE_LOADING_LIST_WITHOUT_LOADING_PLACE"),
  
  CANNOT_CREATE_LOADING_LIST_LOADING_PLACE_NOT_IN_BUSINESSRELATION("CANNOT_CREATE_LOADING_LIST_LOADING_PLACE_NOT_IN_BUSINESSRELATION"),
  
  CANNOT_CREATE_LOADING_LIST_ORDER_NOT_FINISHED("CANNOT_CREATE_LOADING_LIST_ORDER_NOT_FINISHED"),
  
  CANNOT_CREATE_LOADING_LIST_ORDER_NOT_FOUND("CANNOT_CREATE_LOADING_LIST_ORDER_NOT_FOUND"),
  
  NO_COLLI_NUMBERS_LEFT("NO_COLLI_NUMBERS_LEFT"),
  
  WRONG_SHIPPINGORDERANNOUNCEMENT_EDI_STATE("WRONG_SHIPPINGORDERANNOUNCEMENT_EDI_STATE"),
  
  CANNOT_CREATE_LOADING_LIST_ORDER_STATE_NOT_SET("CANNOT_CREATE_LOADING_LIST_ORDER_STATE_NOT_SET"),
  
  WRONG_DELIVERYORDER_WMS_STATE("WRONG_DELIVERYORDER_WMS_STATE"),
  
  ORDER_TO_APPEND_NOT_FOUND("ORDER_TO_APPEND_NOT_FOUND"),
  
  NO_IMAGE_DATA("NO_IMAGE_DATA"),
  
  FILE_TOO_BIG("FILE_TOO_BIG"),
  
  FILE_FORMAT_NOT_SUPPORTED("FILE_FORMAT_NOT_SUPPORTED"),
  
  REPORT_TEMPLATE_NOT_FOUND("REPORT_TEMPLATE_NOT_FOUND"),
  
  ERROR_CREATING_DATASOURCE("ERROR_CREATING_DATASOURCE"),
  
  ERROR_CREATING_PDF_FROM_TEMPLATE("ERROR_CREATING_PDF_FROM_TEMPLATE"),
  
  ERROR_READING_TEMPLATE_FROM_ZIP("ERROR_READING_TEMPLATE_FROM_ZIP"),
  
  ORDER_ANNOUNCEMENT_PDF_EXPORT_EXCEPTION("ORDER_ANNOUNCEMENT_PDF_EXPORT_EXCEPTION"),
  
  ORDER_ANNOUNCEMENT_EXCEPTION("ORDER_ANNOUNCEMENT_EXCEPTION"),
  
  ORDER_COPY_PDF_EXPORT_EXCEPTION("ORDER_COPY_PDF_EXPORT_EXCEPTION"),
  
  ORDER_COPY_HTML_EXPORT_EXCEPTION("ORDER_COPY_HTML_EXPORT_EXCEPTION"),
  
  ORDER_ANNOUNCEMENT_WITHOUT_LOADINGPLACE_EXCEPTION("ORDER_ANNOUNCEMENT_WITHOUT_LOADINGPLACE_EXCEPTION"),
  
  LANGUAGE_TAG_FORMAT_EXCEPTION("LANGUAGE_TAG_FORMAT_EXCEPTION"),
  
  ORDER_COPY_EXCEPTION("ORDER_COPY_EXCEPTION"),
  
  PRINT_TIMEOUT("PRINT_TIMEOUT"),
  
  CONSIGNMENT_OLDER_THAN_3_MONTHS("CONSIGNMENT_OLDER_THAN_3_MONTHS"),
  
  EMAIL_ADDRESSES_ARE_IMMUTABLE("EMAIL_ADDRESSES_ARE_IMMUTABLE"),
  
  BUSINESS_RELATION_ADDRESSES_ARE_IMMUTABLE("BUSINESS_RELATION_ADDRESSES_ARE_IMMUTABLE"),
  
  BUSINESS_RELATION_NOT_EXISTANT("BUSINESS_RELATION_NOT_EXISTANT"),
  
  BUSINESS_RELATION_STATE_IS_IMMUTABLE("BUSINESS_RELATION_STATE_IS_IMMUTABLE"),
  
  BUSINESS_RELATION_CHANGE_FORWARDER("BUSINESS_RELATION_CHANGE_FORWARDER"),
  
  BUSINESS_RELATION_INVALID_OFFER("BUSINESS_RELATION_INVALID_OFFER"),
  
  BUSINESS_RELATION_ADDRESSES_CONTAIN_WRONG_ZIPCODE_PATTERN("BUSINESS_RELATION_ADDRESSES_CONTAIN_WRONG_ZIPCODE_PATTERN"),
  
  BUSINESS_RELATION_ALREADY_ACTIVATED("BUSINESS_RELATION_ALREADY_ACTIVATED"),
  
  BUSINESS_RELATION_WITHOUT_CODEWHITELIST("BUSINESS_RELATION_WITHOUT_CODEWHITELIST"),
  
  FORWARDER_WITHOUT_VALID_CODELIST("FORWARDER_WITHOUT_VALID_CODELIST"),
  
  UPLOAD_TOKEN_NOT_EXISTANT("UPLOAD_TOKEN_NOT_EXISTANT"),
  
  SHIPPING_ORDER_IMPORT_NOT_ALLOWED("SHIPPING_ORDER_IMPORT_NOT_ALLOWED"),
  
  PROCUREMENT_ORDER_IMPORT_NOT_ALLOWED("PROCUREMENT_ORDER_IMPORT_NOT_ALLOWED"),
  
  LOGIN_FAIL("LOGIN_FAIL"),
  
  TOO_MANY_FAILED_LOGINS("TOO_MANY_FAILED_LOGINS"),
  
  LOBSTER_TRANSMISSION_FAILED("LOBSTER_TRANSMISSION_FAILED"),
  
  INVALID_DATE("INVALID_DATE"),
  
  PARSE_CSV_ADDRESS_IMPORT_FILE_FAIL("PARSE_CSV_ADDRESS_IMPORT_FILE_FAIL"),
  
  PARSE_QUERY_PARAMETER_FAIL("PARSE_QUERY_PARAMETER_FAIL"),
  
  ORDER_LABEL_CREATION_FAILED("ORDER_LABEL_CREATION_FAILED"),
  
  EXPORT_SHIPPING_ORDER_PDF_FAILED("EXPORT_SHIPPING_ORDER_PDF_FAILED"),
  
  EXPORT_PROCUREMENT_ORDER_PDF_FAILED("EXPORT_PROCUREMENT_ORDER_PDF_FAILED"),
  
  LOADING_LIST_LABELS_CREATION_FAILED("LOADING_LIST_LABELS_CREATION_FAILED"),
  
  LOADING_LIST_CREATION_FAILED("LOADING_LIST_CREATION_FAILED"),
  
  ROUTING_TABLE_NOT_FOUND("ROUTING_TABLE_NOT_FOUND"),
  
  TEMPLATE_FILE_NOT_READABLE("TEMPLATE_FILE_NOT_READABLE"),
  
  TEMPLATE_NOT_PERSISTABLE("TEMPLATE_NOT_PERSISTABLE"),
  
  BUSINESS_RELATION_STATE_UPDATE_FAILED_WRONG_STATE("BUSINESS_RELATION_STATE_UPDATE_FAILED_WRONG_STATE"),
  
  BUSINESS_RELATION_STATE_UPDATE_FAILED_WRONG_CUSTOMER("BUSINESS_RELATION_STATE_UPDATE_FAILED_WRONG_CUSTOMER"),
  
  BUSINESS_RELATION_ACTIVATION_FAILED_ALREADY_EXISTS_SAME_CUSTOMER("BUSINESS_RELATION_ACTIVATION_FAILED_ALREADY_EXISTS_SAME_CUSTOMER"),
  
  USER_ALREADY_EXISTS("USER_ALREADY_EXISTS"),
  
  ENABLED_FEATURE_INVALID_TIME_RANGE("ENABLED_FEATURE_INVALID_TIME_RANGE"),
  
  ENABLED_FEATURE_ALREADY_ACTIVE("ENABLED_FEATURE_ALREADY_ACTIVE"),
  
  CUSTOMER_ADDRESS_ALREADY_EXISTS("CUSTOMER_ADDRESS_ALREADY_EXISTS"),
  
  INVALID_ARTICLE_SORT_PARAMETER("INVALID_ARTICLE_SORT_PARAMETER"),
  
  EMAIL_TEMPLATE_NOT_FOUND("EMAIL_TEMPLATE_NOT_FOUND"),
  
  FORWARDER_NOT_FOUND("FORWARDER_NOT_FOUND"),
  
  CUSTOMER_NOT_FOUND("CUSTOMER_NOT_FOUND"),
  
  FORWARDER_LINKS_NOT_SET("FORWARDER_LINKS_NOT_SET");

  private String value;

  ErrorCode(String value) {
    this.value = value;
  }

    /**
     * Convert a String into String, as specified in the
     * <a href="https://download.oracle.com/otndocs/jcp/jaxrs-2_0-fr-eval-spec/index.html">See JAX RS 2.0 Specification, section 3.2, p. 12</a>
     */
    public static ErrorCode fromString(String s) {
      for (ErrorCode b : ErrorCode.values()) {
        // using Objects.toString() to be safe if value type non-object type
        // because types like 'int' etc. will be auto-boxed
        if (java.util.Objects.toString(b.value).equals(s)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected string value '" + s + "'");
    }

  @Override
  @JsonValue
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static ErrorCode fromValue(String value) {
    for (ErrorCode b : ErrorCode.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}


