package org.acme.model;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;
import org.acme.model.Context;
import org.acme.model.EnabledFeature;
import org.acme.model.Locale;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonTypeName;



@JsonTypeName("UserContext")
@jakarta.annotation.Generated(value = "org.acme.codegen.languages.JavaJAXRSSpecServerCodegen", date = "2025-11-05T18:35:24.197415100+01:00[Europe/Berlin]", comments = "Generator version: 7.17.0")
public class UserContext   {
  private String id;
  private String userId;
  private String firstname;
  private String lastname;
  private String contextType;
  private String language;
  private Locale locale;
  private @Valid List<@Valid Context> contextRelations = new ArrayList<>();
  private @Valid Set<String> userRights = new LinkedHashSet<>();
  private @Valid Set<@Valid EnabledFeature> features = new LinkedHashSet<>();
  private String forwarderCity;
  private String userFirstname;
  private String userLastname;
  private Long userNumber;
  private String forwarderName;
  private String customerName;
  private Long forwarderNumber;
  private Long customerNumber;
  private Long businessRelationNumber;
  private String businessRelationName;
  private Long accountNumber;

  public UserContext() {
  }

  /**
   * Id of this user context. This id might be either: a base64 encoded json, consisting of all releveant contextrelations fields, or an identifier string generated by the service.
   **/
  public UserContext id(String id) {
    this.id = id;
    return this;
  }

  
  @JsonProperty("id")
  public String getId() {
    return id;
  }

  @JsonProperty("id")
  public void setId(String id) {
    this.id = id;
  }

  /**
   **/
  public UserContext userId(String userId) {
    this.userId = userId;
    return this;
  }

  
  @JsonProperty("userId")
  public String getUserId() {
    return userId;
  }

  @JsonProperty("userId")
  public void setUserId(String userId) {
    this.userId = userId;
  }

  /**
   **/
  public UserContext firstname(String firstname) {
    this.firstname = firstname;
    return this;
  }

  
  @JsonProperty("firstname")
  public String getFirstname() {
    return firstname;
  }

  @JsonProperty("firstname")
  public void setFirstname(String firstname) {
    this.firstname = firstname;
  }

  /**
   **/
  public UserContext lastname(String lastname) {
    this.lastname = lastname;
    return this;
  }

  
  @JsonProperty("lastname")
  public String getLastname() {
    return lastname;
  }

  @JsonProperty("lastname")
  public void setLastname(String lastname) {
    this.lastname = lastname;
  }

  /**
   **/
  public UserContext contextType(String contextType) {
    this.contextType = contextType;
    return this;
  }

  
  @JsonProperty("contextType")
  public String getContextType() {
    return contextType;
  }

  @JsonProperty("contextType")
  public void setContextType(String contextType) {
    this.contextType = contextType;
  }

  /**
   **/
  public UserContext language(String language) {
    this.language = language;
    return this;
  }

  
  @JsonProperty("language")
  public String getLanguage() {
    return language;
  }

  @JsonProperty("language")
  public void setLanguage(String language) {
    this.language = language;
  }

  /**
   **/
  public UserContext locale(Locale locale) {
    this.locale = locale;
    return this;
  }

  
  @JsonProperty("locale")
  @Valid public Locale getLocale() {
    return locale;
  }

  @JsonProperty("locale")
  public void setLocale(Locale locale) {
    this.locale = locale;
  }

  /**
   **/
  public UserContext contextRelations(List<@Valid Context> contextRelations) {
    this.contextRelations = contextRelations;
    return this;
  }

  
  @JsonProperty("contextRelations")
  @Valid public List<@Valid Context> getContextRelations() {
    return contextRelations;
  }

  @JsonProperty("contextRelations")
  public void setContextRelations(List<@Valid Context> contextRelations) {
    this.contextRelations = contextRelations;
  }

  public UserContext addContextRelationsItem(Context contextRelationsItem) {
    if (this.contextRelations == null) {
      this.contextRelations = new ArrayList<>();
    }

    this.contextRelations.add(contextRelationsItem);
    return this;
  }

  public UserContext removeContextRelationsItem(Context contextRelationsItem) {
    if (contextRelationsItem != null && this.contextRelations != null) {
      this.contextRelations.remove(contextRelationsItem);
    }

    return this;
  }
  /**
   * system_masterdata_manage, system_user_manage, system_forwarder_manage
   **/
  public UserContext userRights(Set<String> userRights) {
    this.userRights = userRights;
    return this;
  }

  
  @JsonProperty("userRights")
  public Set<String> getUserRights() {
    return userRights;
  }

  @JsonProperty("userRights")
  @JsonDeserialize(as = LinkedHashSet.class)
  public void setUserRights(Set<String> userRights) {
    this.userRights = userRights;
  }

  public UserContext addUserRightsItem(String userRightsItem) {
    if (this.userRights == null) {
      this.userRights = new LinkedHashSet<>();
    }

    this.userRights.add(userRightsItem);
    return this;
  }

  public UserContext removeUserRightsItem(String userRightsItem) {
    if (userRightsItem != null && this.userRights != null) {
      this.userRights.remove(userRightsItem);
    }

    return this;
  }
  /**
   **/
  public UserContext features(Set<@Valid EnabledFeature> features) {
    this.features = features;
    return this;
  }

  
  @JsonProperty("features")
  @Valid public Set<@Valid EnabledFeature> getFeatures() {
    return features;
  }

  @JsonProperty("features")
  @JsonDeserialize(as = LinkedHashSet.class)
  public void setFeatures(Set<@Valid EnabledFeature> features) {
    this.features = features;
  }

  public UserContext addFeaturesItem(EnabledFeature featuresItem) {
    if (this.features == null) {
      this.features = new LinkedHashSet<>();
    }

    this.features.add(featuresItem);
    return this;
  }

  public UserContext removeFeaturesItem(EnabledFeature featuresItem) {
    if (featuresItem != null && this.features != null) {
      this.features.remove(featuresItem);
    }

    return this;
  }
  /**
   **/
  public UserContext forwarderCity(String forwarderCity) {
    this.forwarderCity = forwarderCity;
    return this;
  }

  
  @JsonProperty("forwarderCity")
  public String getForwarderCity() {
    return forwarderCity;
  }

  @JsonProperty("forwarderCity")
  public void setForwarderCity(String forwarderCity) {
    this.forwarderCity = forwarderCity;
  }

  /**
   **/
  public UserContext userFirstname(String userFirstname) {
    this.userFirstname = userFirstname;
    return this;
  }

  
  @JsonProperty("userFirstname")
  public String getUserFirstname() {
    return userFirstname;
  }

  @JsonProperty("userFirstname")
  public void setUserFirstname(String userFirstname) {
    this.userFirstname = userFirstname;
  }

  /**
   **/
  public UserContext userLastname(String userLastname) {
    this.userLastname = userLastname;
    return this;
  }

  
  @JsonProperty("userLastname")
  public String getUserLastname() {
    return userLastname;
  }

  @JsonProperty("userLastname")
  public void setUserLastname(String userLastname) {
    this.userLastname = userLastname;
  }

  /**
   * The business number of the user
   **/
  public UserContext userNumber(Long userNumber) {
    this.userNumber = userNumber;
    return this;
  }

  
  @JsonProperty("userNumber")
  public Long getUserNumber() {
    return userNumber;
  }

  @JsonProperty("userNumber")
  public void setUserNumber(Long userNumber) {
    this.userNumber = userNumber;
  }

  /**
   **/
  public UserContext forwarderName(String forwarderName) {
    this.forwarderName = forwarderName;
    return this;
  }

  
  @JsonProperty("forwarderName")
  public String getForwarderName() {
    return forwarderName;
  }

  @JsonProperty("forwarderName")
  public void setForwarderName(String forwarderName) {
    this.forwarderName = forwarderName;
  }

  /**
   **/
  public UserContext customerName(String customerName) {
    this.customerName = customerName;
    return this;
  }

  
  @JsonProperty("customerName")
  public String getCustomerName() {
    return customerName;
  }

  @JsonProperty("customerName")
  public void setCustomerName(String customerName) {
    this.customerName = customerName;
  }

  /**
   **/
  public UserContext forwarderNumber(Long forwarderNumber) {
    this.forwarderNumber = forwarderNumber;
    return this;
  }

  
  @JsonProperty("forwarderNumber")
  public Long getForwarderNumber() {
    return forwarderNumber;
  }

  @JsonProperty("forwarderNumber")
  public void setForwarderNumber(Long forwarderNumber) {
    this.forwarderNumber = forwarderNumber;
  }

  /**
   **/
  public UserContext customerNumber(Long customerNumber) {
    this.customerNumber = customerNumber;
    return this;
  }

  
  @JsonProperty("customerNumber")
  public Long getCustomerNumber() {
    return customerNumber;
  }

  @JsonProperty("customerNumber")
  public void setCustomerNumber(Long customerNumber) {
    this.customerNumber = customerNumber;
  }

  /**
   **/
  public UserContext businessRelationNumber(Long businessRelationNumber) {
    this.businessRelationNumber = businessRelationNumber;
    return this;
  }

  
  @JsonProperty("businessRelationNumber")
  public Long getBusinessRelationNumber() {
    return businessRelationNumber;
  }

  @JsonProperty("businessRelationNumber")
  public void setBusinessRelationNumber(Long businessRelationNumber) {
    this.businessRelationNumber = businessRelationNumber;
  }

  /**
   **/
  public UserContext businessRelationName(String businessRelationName) {
    this.businessRelationName = businessRelationName;
    return this;
  }

  
  @JsonProperty("businessRelationName")
  public String getBusinessRelationName() {
    return businessRelationName;
  }

  @JsonProperty("businessRelationName")
  public void setBusinessRelationName(String businessRelationName) {
    this.businessRelationName = businessRelationName;
  }

  /**
   **/
  public UserContext accountNumber(Long accountNumber) {
    this.accountNumber = accountNumber;
    return this;
  }

  
  @JsonProperty("accountNumber")
  public Long getAccountNumber() {
    return accountNumber;
  }

  @JsonProperty("accountNumber")
  public void setAccountNumber(Long accountNumber) {
    this.accountNumber = accountNumber;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserContext userContext = (UserContext) o;
    return Objects.equals(this.id, userContext.id) &&
        Objects.equals(this.userId, userContext.userId) &&
        Objects.equals(this.firstname, userContext.firstname) &&
        Objects.equals(this.lastname, userContext.lastname) &&
        Objects.equals(this.contextType, userContext.contextType) &&
        Objects.equals(this.language, userContext.language) &&
        Objects.equals(this.locale, userContext.locale) &&
        Objects.equals(this.contextRelations, userContext.contextRelations) &&
        Objects.equals(this.userRights, userContext.userRights) &&
        Objects.equals(this.features, userContext.features) &&
        Objects.equals(this.forwarderCity, userContext.forwarderCity) &&
        Objects.equals(this.userFirstname, userContext.userFirstname) &&
        Objects.equals(this.userLastname, userContext.userLastname) &&
        Objects.equals(this.userNumber, userContext.userNumber) &&
        Objects.equals(this.forwarderName, userContext.forwarderName) &&
        Objects.equals(this.customerName, userContext.customerName) &&
        Objects.equals(this.forwarderNumber, userContext.forwarderNumber) &&
        Objects.equals(this.customerNumber, userContext.customerNumber) &&
        Objects.equals(this.businessRelationNumber, userContext.businessRelationNumber) &&
        Objects.equals(this.businessRelationName, userContext.businessRelationName) &&
        Objects.equals(this.accountNumber, userContext.accountNumber);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, userId, firstname, lastname, contextType, language, locale, contextRelations, userRights, features, forwarderCity, userFirstname, userLastname, userNumber, forwarderName, customerName, forwarderNumber, customerNumber, businessRelationNumber, businessRelationName, accountNumber);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserContext {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    firstname: ").append(toIndentedString(firstname)).append("\n");
    sb.append("    lastname: ").append(toIndentedString(lastname)).append("\n");
    sb.append("    contextType: ").append(toIndentedString(contextType)).append("\n");
    sb.append("    language: ").append(toIndentedString(language)).append("\n");
    sb.append("    locale: ").append(toIndentedString(locale)).append("\n");
    sb.append("    contextRelations: ").append(toIndentedString(contextRelations)).append("\n");
    sb.append("    userRights: ").append(toIndentedString(userRights)).append("\n");
    sb.append("    features: ").append(toIndentedString(features)).append("\n");
    sb.append("    forwarderCity: ").append(toIndentedString(forwarderCity)).append("\n");
    sb.append("    userFirstname: ").append(toIndentedString(userFirstname)).append("\n");
    sb.append("    userLastname: ").append(toIndentedString(userLastname)).append("\n");
    sb.append("    userNumber: ").append(toIndentedString(userNumber)).append("\n");
    sb.append("    forwarderName: ").append(toIndentedString(forwarderName)).append("\n");
    sb.append("    customerName: ").append(toIndentedString(customerName)).append("\n");
    sb.append("    forwarderNumber: ").append(toIndentedString(forwarderNumber)).append("\n");
    sb.append("    customerNumber: ").append(toIndentedString(customerNumber)).append("\n");
    sb.append("    businessRelationNumber: ").append(toIndentedString(businessRelationNumber)).append("\n");
    sb.append("    businessRelationName: ").append(toIndentedString(businessRelationName)).append("\n");
    sb.append("    accountNumber: ").append(toIndentedString(accountNumber)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


}

